### ISSUE TITLE
'Unexpected token .' when running the sample new ION.DID() creation

### ISSUE THREAD

**Issue by syedshahzebhasnain** [decentralized-identity/ion-tools#13]
Package version : 0.1.0
Node version : v10.23.0
OS : Ubuntu 18 / Windows 10

I am trying to create a new DID from the sample on the readme. 
`let did = new ION.DID({
      content: {.....`

Error Description : 

`/home/syed/ION/node_modules/@decentralized-identity/ion-tools/ion.js/lib.js:173
          servicesToAdd: op.content?.addServices,
                                    ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/syed/AzureVC_ION/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`

**Comment by syedshahzebhasnain** [comment]
Ok I think I found the issue.
The error was because of the older version of Node.

Tested again with Node 14.17.4 LTS and it works fine.

Closing this now.
