### ISSUE TITLE
While trying to anchor I am getting Get challenge service not available error

### ISSUE THREAD

**Issue by sakalis** [decentralized-identity/ion-tools#64]
I am trying to anchor the did to the default address and I am getting the following error

Getting challenge from: https://beta.ion.msidentity.com/api/v1.0/proof-of-work-challenge
C:\tmp\ion\node_modules\@decentralized-identity\ion-pow-sdk\src\index.js:27
            throw new Error('Get challenge service not available')
                  ^

Error: Get challenge service not available
    at IonProofOfWork.submitIonRequest (C:\tmp\ion\node_modules\@decentralized-identity\ion-pow-sdk\src\index.js:27:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (C:\tmp\ion\index2.js:45:30)

Node.js v20.9.0

**Comment by macterra** [comment]
Me too. Any work arounds?

**Comment by macterra** [comment]
Just for the record, instead of using the anchor function I used the API directly, e.g.

```
        const getAnchor = await axios.post('http://localhost:3000/operations/', createRequest);
        const anchor = getAnchor.data;
```
